package com.zhao.craneslidetest.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zhao.craneslidetest.beans.CraneResultChartData;
import com.zhao.craneslidetest.beans.CraneType;

import com.zhao.craneslidetest.dao.CraneResultChartDataDao;
import com.zhao.craneslidetest.dao.CraneTypeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig craneResultChartDataDaoConfig;
    private final DaoConfig craneTypeDaoConfig;

    private final CraneResultChartDataDao craneResultChartDataDao;
    private final CraneTypeDao craneTypeDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        craneResultChartDataDaoConfig = daoConfigMap.get(CraneResultChartDataDao.class).clone();
        craneResultChartDataDaoConfig.initIdentityScope(type);

        craneTypeDaoConfig = daoConfigMap.get(CraneTypeDao.class).clone();
        craneTypeDaoConfig.initIdentityScope(type);

        craneResultChartDataDao = new CraneResultChartDataDao(craneResultChartDataDaoConfig, this);
        craneTypeDao = new CraneTypeDao(craneTypeDaoConfig, this);

        registerDao(CraneResultChartData.class, craneResultChartDataDao);
        registerDao(CraneType.class, craneTypeDao);
    }
    
    public void clear() {
        craneResultChartDataDaoConfig.clearIdentityScope();
        craneTypeDaoConfig.clearIdentityScope();
    }

    public CraneResultChartDataDao getCraneResultChartDataDao() {
        return craneResultChartDataDao;
    }

    public CraneTypeDao getCraneTypeDao() {
        return craneTypeDao;
    }

}
